
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: unsaved
* name: CogFont
* family: MS Shell Dlg 2
* size: 11
* style: Обычный
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: monospaced
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Edge 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>



#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x20[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x20 = { image_data_CogFont_0x20,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x21[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x21 = { image_data_CogFont_0x21,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x22[26] = {
    // ███████████
    // ███████████
    // ███∙█∙█████
    // ███∙█∙█████
    // ███∙█∙█████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x22 = { image_data_CogFont_0x22,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x23[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙█∙████
    // ████∙█∙████
    // ██∙∙∙∙∙∙███
    // ███∙█∙█████
    // ███∙█∙█████
    // █∙∙∙∙∙∙████
    // ██∙█∙██████
    // ██∙█∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf5, 0xe0, 
    0xf5, 0xe0, 
    0xc0, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0x81, 0xe0, 
    0xd7, 0xe0, 
    0xd7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x23 = { image_data_CogFont_0x23,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x24[26] = {
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ███∙∙∙∙████
    // ██∙█∙██████
    // ██∙█∙██████
    // ███∙∙∙█████
    // ████∙█∙████
    // ████∙█∙████
    // ██∙∙∙∙█████
    // ████∙██████
    // ████∙██████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xe1, 0xe0, 
    0xd7, 0xe0, 
    0xd7, 0xe0, 
    0xe3, 0xe0, 
    0xf5, 0xe0, 
    0xf5, 0xe0, 
    0xc3, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0
};
static const tImage CogFont_0x24 = { image_data_CogFont_0x24,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x25[26] = {
    // ███████████
    // ███████████
    // ███████████
    // █∙∙███∙████
    // ∙██∙██∙████
    // ∙██∙█∙█████
    // █∙∙██∙█████
    // ████∙██∙∙██
    // ████∙█∙██∙█
    // ███∙██∙██∙█
    // ███∙███∙∙██
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9d, 0xe0, 
    0x6d, 0xe0, 
    0x6b, 0xe0, 
    0x9b, 0xe0, 
    0xf6, 0x60, 
    0xf5, 0xa0, 
    0xed, 0xa0, 
    0xee, 0x60, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x25 = { image_data_CogFont_0x25,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x26[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙██████
    // ██∙██∙█████
    // ██∙██∙█████
    // ███∙∙██∙███
    // ██∙██∙█∙███
    // ██∙███∙████
    // ██∙███∙∙███
    // ███∙∙∙██∙██
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe7, 0xe0, 
    0xdb, 0xe0, 
    0xdb, 0xe0, 
    0xe6, 0xe0, 
    0xda, 0xe0, 
    0xdd, 0xe0, 
    0xdc, 0xe0, 
    0xe3, 0x60, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x26 = { image_data_CogFont_0x26,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x27[26] = {
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x27 = { image_data_CogFont_0x27,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x28[26] = {
    // ███████████
    // ███████████
    // █████∙█████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ████∙██████
    // ████∙██████
    // █████∙█████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xfb, 0xe0
};
static const tImage CogFont_0x28 = { image_data_CogFont_0x28,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x29[26] = {
    // ███████████
    // ███████████
    // ███∙███████
    // ████∙██████
    // ████∙██████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xef, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0
};
static const tImage CogFont_0x29 = { image_data_CogFont_0x29,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x2a[26] = {
    // ███████████
    // ███████████
    // ████∙██████
    // ██∙█∙█∙████
    // ███∙∙∙█████
    // ██∙█∙█∙████
    // ████∙██████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xd5, 0xe0, 
    0xe3, 0xe0, 
    0xd5, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x2a = { image_data_CogFont_0x2a,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x2b[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // █∙∙∙∙∙∙∙███
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0x80, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x2b = { image_data_CogFont_0x2b,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x2c[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0
};
static const tImage CogFont_0x2c = { image_data_CogFont_0x2c,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x2d[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x2d = { image_data_CogFont_0x2d,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x2e[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x2e = { image_data_CogFont_0x2e,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x2f[26] = {
    // ███████████
    // ███████████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0
};
static const tImage CogFont_0x2f = { image_data_CogFont_0x2f,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x30[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x30 = { image_data_CogFont_0x30,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x31[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ███∙∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xe7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x31 = { image_data_CogFont_0x31,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x32[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██████∙████
    // █████∙█████
    // ████∙██████
    // ███∙███████
    // ██∙████████
    // ██∙∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xfd, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0, 
    0xdf, 0xe0, 
    0xc1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x32 = { image_data_CogFont_0x32,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x33[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██████∙████
    // ████∙∙█████
    // ██████∙████
    // ██████∙████
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xfd, 0xe0, 
    0xf3, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x33 = { image_data_CogFont_0x33,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x34[26] = {
    // ███████████
    // ███████████
    // ███████████
    // █████∙█████
    // ████∙∙█████
    // ███∙█∙█████
    // ██∙██∙█████
    // ██∙∙∙∙∙████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xfb, 0xe0, 
    0xf3, 0xe0, 
    0xeb, 0xe0, 
    0xdb, 0xe0, 
    0xc1, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x34 = { image_data_CogFont_0x34,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x35[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙████
    // ██∙████████
    // ██∙████████
    // ██∙∙∙∙█████
    // ██████∙████
    // ██████∙████
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc1, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xc3, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x35 = { image_data_CogFont_0x35,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x36[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙█████
    // ███∙███████
    // ██∙████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf3, 0xe0, 
    0xef, 0xe0, 
    0xdf, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x36 = { image_data_CogFont_0x36,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x37[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙████
    // ██████∙████
    // █████∙█████
    // █████∙█████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    // ███∙███████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc1, 0xe0, 
    0xfd, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x37 = { image_data_CogFont_0x37,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x38[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x38 = { image_data_CogFont_0x38,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x39[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙∙████
    // ██████∙████
    // █████∙█████
    // ███∙∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe1, 0xe0, 
    0xfd, 0xe0, 
    0xfb, 0xe0, 
    0xe7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x39 = { image_data_CogFont_0x39,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x3a[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x3a = { image_data_CogFont_0x3a,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x3b[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0
};
static const tImage CogFont_0x3b = { image_data_CogFont_0x3b,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x3c[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████∙███
    // █████∙∙████
    // ███∙∙██████
    // ██∙████████
    // ███∙∙██████
    // █████∙∙████
    // ███████∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xfe, 0xe0, 
    0xf9, 0xe0, 
    0xe7, 0xe0, 
    0xdf, 0xe0, 
    0xe7, 0xe0, 
    0xf9, 0xe0, 
    0xfe, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x3c = { image_data_CogFont_0x3c,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x3d[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙∙∙∙∙∙███
    // ███████████
    // █∙∙∙∙∙∙∙███
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x80, 0xe0, 
    0xff, 0xe0, 
    0x80, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x3d = { image_data_CogFont_0x3d,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x3e[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙████████
    // ███∙∙██████
    // █████∙∙████
    // ███████∙███
    // █████∙∙████
    // ███∙∙██████
    // ██∙████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdf, 0xe0, 
    0xe7, 0xe0, 
    0xf9, 0xe0, 
    0xfe, 0xe0, 
    0xf9, 0xe0, 
    0xe7, 0xe0, 
    0xdf, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x3e = { image_data_CogFont_0x3e,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x3f[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██████∙████
    // ██████∙████
    // █████∙█████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x3f = { image_data_CogFont_0x3f,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x40[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙████
    // █∙█████∙███
    // ∙██∙∙∙██∙██
    // ∙█∙██∙██∙██
    // ∙█∙██∙██∙██
    // ∙█∙██∙██∙██
    // ∙██∙∙∙∙∙███
    // █∙█████████
    // ██∙∙∙∙█████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc1, 0xe0, 
    0xbe, 0xe0, 
    0x63, 0x60, 
    0x5b, 0x60, 
    0x5b, 0x60, 
    0x5b, 0x60, 
    0x60, 0xe0, 
    0xbf, 0xe0, 
    0xc3, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x40 = { image_data_CogFont_0x40,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x41[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙█████
    // ████∙∙█████
    // ███∙██∙████
    // ███∙██∙████
    // ███∙██∙████
    // ██∙∙∙∙∙∙███
    // ██∙████∙███
    // ██∙████∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf3, 0xe0, 
    0xf3, 0xe0, 
    0xed, 0xe0, 
    0xed, 0xe0, 
    0xed, 0xe0, 
    0xc0, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x41 = { image_data_CogFont_0x41,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x42[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xc3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x42 = { image_data_CogFont_0x42,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x43[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙∙███
    // ███∙███████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ███∙███████
    // ████∙∙∙∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf0, 0xe0, 
    0xef, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xef, 0xe0, 
    0xf0, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x43 = { image_data_CogFont_0x43,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x44[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙███∙████
    // ██∙∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xdd, 0xe0, 
    0xc3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x44 = { image_data_CogFont_0x44,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x45[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙████
    // ██∙████████
    // ██∙████████
    // ██∙∙∙∙█████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ██∙∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc1, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xc3, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xc1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x45 = { image_data_CogFont_0x45,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x46[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙████
    // ██∙████████
    // ██∙████████
    // ██∙∙∙∙∙████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc1, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xc1, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x46 = { image_data_CogFont_0x46,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x47[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙∙███
    // ███∙███████
    // ██∙████████
    // ██∙████████
    // ██∙██∙∙∙███
    // ██∙████∙███
    // ███∙███∙███
    // ████∙∙∙∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf0, 0xe0, 
    0xef, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xd8, 0xe0, 
    0xde, 0xe0, 
    0xee, 0xe0, 
    0xf0, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x47 = { image_data_CogFont_0x47,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x48[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙∙∙∙∙∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xc0, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x48 = { image_data_CogFont_0x48,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x49[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x49 = { image_data_CogFont_0x49,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x4a[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙████
    // ██████∙████
    // ██████∙████
    // ██████∙████
    // ██████∙████
    // ██████∙████
    // ██████∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf1, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x4a = { image_data_CogFont_0x4a,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x4b[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ██∙██∙█████
    // ██∙█∙██████
    // ██∙∙███████
    // ██∙∙███████
    // ██∙█∙██████
    // ██∙██∙█████
    // ██∙███∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xdb, 0xe0, 
    0xd7, 0xe0, 
    0xcf, 0xe0, 
    0xcf, 0xe0, 
    0xd7, 0xe0, 
    0xdb, 0xe0, 
    0xdd, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x4b = { image_data_CogFont_0x4b,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x4c[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xe1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x4c = { image_data_CogFont_0x4c,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x4d[26] = {
    // ███████████
    // ███████████
    // ███████████
    // █∙∙███∙∙███
    // █∙∙███∙∙███
    // █∙█∙█∙█∙███
    // █∙█∙█∙█∙███
    // █∙██∙██∙███
    // █∙██∙██∙███
    // █∙█████∙███
    // █∙█████∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x9c, 0xe0, 
    0x9c, 0xe0, 
    0xaa, 0xe0, 
    0xaa, 0xe0, 
    0xb6, 0xe0, 
    0xb6, 0xe0, 
    0xbe, 0xe0, 
    0xbe, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x4d = { image_data_CogFont_0x4d,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x4e[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙███∙███
    // ██∙∙███∙███
    // ██∙█∙██∙███
    // ██∙█∙██∙███
    // ██∙██∙█∙███
    // ██∙██∙█∙███
    // ██∙███∙∙███
    // ██∙███∙∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xce, 0xe0, 
    0xce, 0xe0, 
    0xd6, 0xe0, 
    0xd6, 0xe0, 
    0xda, 0xe0, 
    0xda, 0xe0, 
    0xdc, 0xe0, 
    0xdc, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x4e = { image_data_CogFont_0x4e,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x4f[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // █∙█████∙███
    // █∙█████∙███
    // █∙█████∙███
    // █∙█████∙███
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xbe, 0xe0, 
    0xbe, 0xe0, 
    0xbe, 0xe0, 
    0xbe, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x4f = { image_data_CogFont_0x4f,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x50[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙∙∙∙█████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xc3, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x50 = { image_data_CogFont_0x50,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x51[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // █∙█████∙███
    // █∙█████∙███
    // █∙█████∙███
    // █∙█████∙███
    // ██∙███∙████
    // ███∙∙∙█████
    // █████∙█████
    // ██████∙∙███
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xbe, 0xe0, 
    0xbe, 0xe0, 
    0xbe, 0xe0, 
    0xbe, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xfb, 0xe0, 
    0xfc, 0xe0
};
static const tImage CogFont_0x51 = { image_data_CogFont_0x51,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x52[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙∙∙∙█████
    // ██∙██∙█████
    // ██∙███∙████
    // ██∙████∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xc3, 0xe0, 
    0xdb, 0xe0, 
    0xdd, 0xe0, 
    0xde, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x52 = { image_data_CogFont_0x52,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x53[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙∙████
    // ██∙████████
    // ██∙████████
    // ███∙∙∙█████
    // ██████∙████
    // ██████∙████
    // ██████∙████
    // ██∙∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe1, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xe3, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xc3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x53 = { image_data_CogFont_0x53,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x54[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc1, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x54 = { image_data_CogFont_0x54,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x55[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ██∙████∙███
    // ███∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xde, 0xe0, 
    0xe1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x55 = { image_data_CogFont_0x55,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x56[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙█∙█████
    // ███∙█∙█████
    // ███∙█∙█████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x56 = { image_data_CogFont_0x56,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x57[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ∙███∙███∙██
    // ∙███∙███∙██
    // ∙███∙███∙██
    // █∙█∙█∙█∙███
    // █∙█∙█∙█∙███
    // █∙█∙█∙█∙███
    // ██∙███∙████
    // ██∙███∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x77, 0x60, 
    0x77, 0x60, 
    0x77, 0x60, 
    0xaa, 0xe0, 
    0xaa, 0xe0, 
    0xaa, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x57 = { image_data_CogFont_0x57,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x58[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙█∙█████
    // ████∙██████
    // ████∙██████
    // ███∙█∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xeb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xeb, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x58 = { image_data_CogFont_0x58,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x59[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙█∙█████
    // ███∙█∙█████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x59 = { image_data_CogFont_0x59,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x5a[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙████
    // ██████∙████
    // █████∙█████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    // ██∙████████
    // ██∙∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc1, 0xe0, 
    0xfd, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0, 
    0xdf, 0xe0, 
    0xc1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x5a = { image_data_CogFont_0x5a,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x5b[26] = {
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙∙∙█████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xe3, 0xe0
};
static const tImage CogFont_0x5b = { image_data_CogFont_0x5b,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x5c[26] = {
    // ███████████
    // ███████████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0
};
static const tImage CogFont_0x5c = { image_data_CogFont_0x5c,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x5d[26] = {
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // ███∙∙∙█████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xe3, 0xe0
};
static const tImage CogFont_0x5d = { image_data_CogFont_0x5d,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x5e[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ███∙█∙█████
    // ██∙███∙████
    // █∙█████∙███
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xeb, 0xe0, 
    0xdd, 0xe0, 
    0xbe, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x5e = { image_data_CogFont_0x5e,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x5f[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙∙∙███
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc0, 0xe0
};
static const tImage CogFont_0x5f = { image_data_CogFont_0x5f,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x60[26] = {
    // ███████████
    // ███████████
    // ███∙███████
    // ████∙██████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xef, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x60 = { image_data_CogFont_0x60,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x61[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██████∙████
    // ███∙∙∙∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xfd, 0xe0, 
    0xe1, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x61 = { image_data_CogFont_0x61,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x62[26] = {
    // ███████████
    // ███████████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xc3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x62 = { image_data_CogFont_0x62,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x63[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ████∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf1, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xf1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x63 = { image_data_CogFont_0x63,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x64[26] = {
    // ███████████
    // ███████████
    // ██████∙████
    // ██████∙████
    // ██████∙████
    // ███∙∙∙∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0, 
    0xe1, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x64 = { image_data_CogFont_0x64,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x65[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██∙∙∙∙∙████
    // ██∙████████
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xc1, 0xe0, 
    0xdf, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x65 = { image_data_CogFont_0x65,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x66[26] = {
    // ███████████
    // ███████████
    // ████∙∙█████
    // ███∙███████
    // ███∙███████
    // ███∙∙∙█████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf3, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xe3, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x66 = { image_data_CogFont_0x66,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x67[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙∙████
    // ██████∙████
    // ███∙∙∙█████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe1, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe1, 0xe0, 
    0xfd, 0xe0, 
    0xe3, 0xe0
};
static const tImage CogFont_0x67 = { image_data_CogFont_0x67,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x68[26] = {
    // ███████████
    // ███████████
    // ██∙████████
    // ██∙████████
    // ██∙████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x68 = { image_data_CogFont_0x68,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x69[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ████∙██████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x69 = { image_data_CogFont_0x69,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x6a[26] = {
    // ███████████
    // ███████████
    // ███████████
    // █████∙█████
    // ███████████
    // ████∙∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // ████∙██████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xfb, 0xe0, 
    0xff, 0xe0, 
    0xf3, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0
};
static const tImage CogFont_0x6a = { image_data_CogFont_0x6a,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x6b[26] = {
    // ███████████
    // ███████████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙██∙████
    // ███∙█∙█████
    // ███∙∙██████
    // ███∙█∙█████
    // ███∙██∙████
    // ███∙███∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xed, 0xe0, 
    0xeb, 0xe0, 
    0xe7, 0xe0, 
    0xeb, 0xe0, 
    0xed, 0xe0, 
    0xee, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x6b = { image_data_CogFont_0x6b,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x6c[26] = {
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x6c = { image_data_CogFont_0x6c,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x6d[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙∙∙█∙∙████
    // █∙██∙██∙███
    // █∙██∙██∙███
    // █∙██∙██∙███
    // █∙██∙██∙███
    // █∙██∙██∙███
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0x89, 0xe0, 
    0xb6, 0xe0, 
    0xb6, 0xe0, 
    0xb6, 0xe0, 
    0xb6, 0xe0, 
    0xb6, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x6d = { image_data_CogFont_0x6d,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x6e[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x6e = { image_data_CogFont_0x6e,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x6f[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x6f = { image_data_CogFont_0x6f,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x70[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙∙∙█████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙∙∙∙█████
    // ██∙████████
    // ██∙████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xc3, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xc3, 0xe0, 
    0xdf, 0xe0, 
    0xdf, 0xe0
};
static const tImage CogFont_0x70 = { image_data_CogFont_0x70,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x71[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙∙████
    // ██████∙████
    // ██████∙████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe1, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe1, 0xe0, 
    0xfd, 0xe0, 
    0xfd, 0xe0
};
static const tImage CogFont_0x71 = { image_data_CogFont_0x71,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x72[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙█∙█████
    // ███∙∙██████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xeb, 0xe0, 
    0xe7, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x72 = { image_data_CogFont_0x72,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x73[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ████∙∙∙████
    // ███∙███████
    // ███∙∙██████
    // █████∙∙████
    // ██████∙████
    // ███∙∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf1, 0xe0, 
    0xef, 0xe0, 
    0xe7, 0xe0, 
    0xf9, 0xe0, 
    0xfd, 0xe0, 
    0xe3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x73 = { image_data_CogFont_0x73,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x74[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███∙███████
    // ███∙███████
    // ███∙∙∙█████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ███∙███████
    // ████∙∙█████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xe3, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0, 
    0xf3, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x74 = { image_data_CogFont_0x74,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x75[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xe1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x75 = { image_data_CogFont_0x75,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x76[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙█∙█████
    // ███∙█∙█████
    // ████∙██████
    // ████∙██████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x76 = { image_data_CogFont_0x76,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x77[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // █∙██∙██∙███
    // █∙██∙██∙███
    // █∙█∙█∙█∙███
    // █∙█∙█∙█∙███
    // ██∙███∙████
    // ██∙███∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xb6, 0xe0, 
    0xb6, 0xe0, 
    0xaa, 0xe0, 
    0xaa, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x77 = { image_data_CogFont_0x77,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x78[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ███∙█∙█████
    // ████∙██████
    // ████∙██████
    // ███∙█∙█████
    // ██∙███∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xeb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xeb, 0xe0, 
    0xdd, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x78 = { image_data_CogFont_0x78,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x79[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙███∙████
    // ██∙███∙████
    // ███∙█∙█████
    // ███∙█∙█████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    // ███∙███████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xdd, 0xe0, 
    0xdd, 0xe0, 
    0xeb, 0xe0, 
    0xeb, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0, 
    0xef, 0xe0
};
static const tImage CogFont_0x79 = { image_data_CogFont_0x79,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x7a[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███∙∙∙∙████
    // ██████∙████
    // █████∙█████
    // ████∙██████
    // ███∙███████
    // ███∙∙∙∙████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xe1, 0xe0, 
    0xfd, 0xe0, 
    0xfb, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0, 
    0xe1, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x7a = { image_data_CogFont_0x7a,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x7b[26] = {
    // ███████████
    // ███████████
    // ██████∙████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // ███∙∙██████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // █████∙█████
    // ██████∙████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xfd, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xe7, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfb, 0xe0, 
    0xfd, 0xe0
};
static const tImage CogFont_0x7b = { image_data_CogFont_0x7b,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x7c[26] = {
    // ███████████
    // ███████████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0
};
static const tImage CogFont_0x7c = { image_data_CogFont_0x7c,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x7d[26] = {
    // ███████████
    // ███████████
    // ███∙███████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // █████∙∙████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ████∙██████
    // ███∙███████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xef, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf9, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xf7, 0xe0, 
    0xef, 0xe0
};
static const tImage CogFont_0x7d = { image_data_CogFont_0x7d,
    11, 13, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_CogFont_0x7e[26] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ██∙∙███∙███
    // █∙██∙██∙███
    // █∙███∙∙████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xce, 0xe0, 
    0xb6, 0xe0, 
    0xb9, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0, 
    0xff, 0xe0
};
static const tImage CogFont_0x7e = { image_data_CogFont_0x7e,
    11, 13, 8};
#endif


static const tChar CogFont_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &CogFont_0x20},
#else
  // character: ' ' == ''
  {0x20, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &CogFont_0x21},
#else
  // character: '!' == ''
  {0x21, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &CogFont_0x22},
#else
  // character: '"' == ''
  {0x22, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &CogFont_0x23},
#else
  // character: '#' == ''
  {0x23, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &CogFont_0x24},
#else
  // character: '$' == ''
  {0x24, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &CogFont_0x25},
#else
  // character: '%' == ''
  {0x25, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &CogFont_0x26},
#else
  // character: '&' == ''
  {0x26, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &CogFont_0x27},
#else
  // character: ''' == ''
  {0x27, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &CogFont_0x28},
#else
  // character: '(' == ''
  {0x28, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &CogFont_0x29},
#else
  // character: ')' == ''
  {0x29, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &CogFont_0x2a},
#else
  // character: '*' == ''
  {0x2a, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &CogFont_0x2b},
#else
  // character: '+' == ''
  {0x2b, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &CogFont_0x2c},
#else
  // character: ',' == ''
  {0x2c, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &CogFont_0x2d},
#else
  // character: '-' == ''
  {0x2d, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &CogFont_0x2e},
#else
  // character: '.' == ''
  {0x2e, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &CogFont_0x2f},
#else
  // character: '/' == ''
  {0x2f, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &CogFont_0x30},
#else
  // character: '0' == ''
  {0x30, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &CogFont_0x31},
#else
  // character: '1' == ''
  {0x31, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &CogFont_0x32},
#else
  // character: '2' == ''
  {0x32, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &CogFont_0x33},
#else
  // character: '3' == ''
  {0x33, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &CogFont_0x34},
#else
  // character: '4' == ''
  {0x34, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &CogFont_0x35},
#else
  // character: '5' == ''
  {0x35, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &CogFont_0x36},
#else
  // character: '6' == ''
  {0x36, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &CogFont_0x37},
#else
  // character: '7' == ''
  {0x37, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &CogFont_0x38},
#else
  // character: '8' == ''
  {0x38, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &CogFont_0x39},
#else
  // character: '9' == ''
  {0x39, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &CogFont_0x3a},
#else
  // character: ':' == ''
  {0x3a, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &CogFont_0x3b},
#else
  // character: ';' == ''
  {0x3b, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &CogFont_0x3c},
#else
  // character: '<' == ''
  {0x3c, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &CogFont_0x3d},
#else
  // character: '=' == ''
  {0x3d, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &CogFont_0x3e},
#else
  // character: '>' == ''
  {0x3e, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &CogFont_0x3f},
#else
  // character: '?' == ''
  {0x3f, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &CogFont_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &CogFont_0x41},
#else
  // character: 'A' == ''
  {0x41, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &CogFont_0x42},
#else
  // character: 'B' == ''
  {0x42, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &CogFont_0x43},
#else
  // character: 'C' == ''
  {0x43, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &CogFont_0x44},
#else
  // character: 'D' == ''
  {0x44, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &CogFont_0x45},
#else
  // character: 'E' == ''
  {0x45, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &CogFont_0x46},
#else
  // character: 'F' == ''
  {0x46, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &CogFont_0x47},
#else
  // character: 'G' == ''
  {0x47, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &CogFont_0x48},
#else
  // character: 'H' == ''
  {0x48, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &CogFont_0x49},
#else
  // character: 'I' == ''
  {0x49, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &CogFont_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &CogFont_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &CogFont_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &CogFont_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &CogFont_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &CogFont_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &CogFont_0x50},
#else
  // character: 'P' == ''
  {0x50, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &CogFont_0x51},
#else
  // character: 'Q' == ''
  {0x51, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &CogFont_0x52},
#else
  // character: 'R' == ''
  {0x52, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &CogFont_0x53},
#else
  // character: 'S' == ''
  {0x53, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &CogFont_0x54},
#else
  // character: 'T' == ''
  {0x54, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &CogFont_0x55},
#else
  // character: 'U' == ''
  {0x55, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &CogFont_0x56},
#else
  // character: 'V' == ''
  {0x56, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &CogFont_0x57},
#else
  // character: 'W' == ''
  {0x57, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &CogFont_0x58},
#else
  // character: 'X' == ''
  {0x58, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &CogFont_0x59},
#else
  // character: 'Y' == ''
  {0x59, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &CogFont_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &CogFont_0x5b},
#else
  // character: '[' == ''
  {0x5b, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &CogFont_0x5c},
#else
  // character: '\' == ''
  {0x5c, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &CogFont_0x5d},
#else
  // character: ']' == ''
  {0x5d, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &CogFont_0x5e},
#else
  // character: '^' == ''
  {0x5e, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &CogFont_0x5f},
#else
  // character: '_' == ''
  {0x5f, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &CogFont_0x60},
#else
  // character: '`' == ''
  {0x60, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &CogFont_0x61},
#else
  // character: 'a' == ''
  {0x61, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &CogFont_0x62},
#else
  // character: 'b' == ''
  {0x62, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &CogFont_0x63},
#else
  // character: 'c' == ''
  {0x63, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &CogFont_0x64},
#else
  // character: 'd' == ''
  {0x64, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &CogFont_0x65},
#else
  // character: 'e' == ''
  {0x65, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &CogFont_0x66},
#else
  // character: 'f' == ''
  {0x66, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &CogFont_0x67},
#else
  // character: 'g' == ''
  {0x67, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &CogFont_0x68},
#else
  // character: 'h' == ''
  {0x68, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &CogFont_0x69},
#else
  // character: 'i' == ''
  {0x69, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &CogFont_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &CogFont_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'l'
  {0x6c, &CogFont_0x6c},
#else
  // character: 'l' == ''
  {0x6c, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &CogFont_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &CogFont_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &CogFont_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &CogFont_0x70},
#else
  // character: 'p' == ''
  {0x70, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &CogFont_0x71},
#else
  // character: 'q' == ''
  {0x71, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &CogFont_0x72},
#else
  // character: 'r' == ''
  {0x72, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &CogFont_0x73},
#else
  // character: 's' == ''
  {0x73, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &CogFont_0x74},
#else
  // character: 't' == ''
  {0x74, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &CogFont_0x75},
#else
  // character: 'u' == ''
  {0x75, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &CogFont_0x76},
#else
  // character: 'v' == ''
  {0x76, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &CogFont_0x77},
#else
  // character: 'w' == ''
  {0x77, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &CogFont_0x78},
#else
  // character: 'x' == ''
  {0x78, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &CogFont_0x79},
#else
  // character: 'y' == ''
  {0x79, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &CogFont_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &CogFont_0x7b},
#else
  // character: '{' == ''
  {0x7b, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &CogFont_0x7c},
#else
  // character: '|' == ''
  {0x7c, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &CogFont_0x7d},
#else
  // character: '}' == ''
  {0x7d, &CogFont_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &CogFont_0x7e}
#else
  // character: '~' == ''
  {0x7e, &CogFont_0x}
#endif

};


const tFont CogFont = { 95, CogFont_array };

